### ISSUE TITLE
Certain assets appear pixelated

### ISSUE THREAD

**Issue by skllcrn** [zeit/next-site#293] opened 2019-03-28 17:46 UTC
Latest Chrome on macOS 10.14.5 

Certain assets on Next.js blog posts appear pixelated @1x, including the Next.js logo in the header, back arrow at the end of a post and the ZEIT logo in the footer:

![image](https://user-images.githubusercontent.com/8440026/55180341-b3c65600-5189-11e9-824e-f9f712d1bce1.png)

![image](https://user-images.githubusercontent.com/8440026/55180394-cfc9f780-5189-11e9-8dc6-a022aca5d745.png)

**Comment by lfades** [comment] 2019-07-19 16:28
@skllcrn Can you update the issue with more details including OS, browser, screen resolution and related 🙏

**Comment by timneutkens** [comment] 2019-08-11 19:48
I'm going to close this as I can't reproduce.

**Closed by timneutkens** 2019-08-11 19:48 UTC
